name: Setup

inputs:
  terraform_version:
    required: true

runs:
  using: composite
  steps:
    - name: Check for the Terraform binary
      id: terraform-bin
      uses: ./.github/actions/check-terraform-bin
    - name: Setup Terraform & cache its binary
      if: steps.terraform-bin.outputs.exists != 'true'
      uses: ./.github/actions/terraform-bin
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Allow Terraform binary be used by non-roots 
      run: sudo cp output/terraform/bin /usr/local/bin/terraform
      shell: bash