name: Check Terraform binary

runs:
  using: composite
  steps:
    - name: Download Terraform binary
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: terraform-bin
    - run: ls output/terraform
      continue-on-error: true
      shell: bash
    - name: Check if Terraform binary exists
      id: terraform-bin
      run: |
        if [ -e output/terraform/bin ]; then 
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Terraform binary file already exists..."
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Terraform binary file does not exist..."
        fi
      shell: bash