name: Check Terraform init

runs:
  using: composite
  steps:
    - name: Download Terraform init files
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: terraform-init
    - run: ls output/terraform
      continue-on-error: true
      shell: bash
    - name: Check if Terraform init files exist
      id: terraform-init
      run: |
        if [ -e output/terraform/init ]; then 
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "Terraform init files already exist..."
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "Terraform init files do not exist..."
        fi
      shell: bash