name: Check Terraform init

runs:
  using: composite
  steps:
    - name: Check if Terraform init files exist
      id: terraform-init
      run: |
        if [ -e output/terraform/init ]; then 
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Download Terraform binary
      if: steps.terraform-init.outputs.exists != true
      uses: actions/download-artifact@v4
      with:
        name: terraform-init