name: Generate Terraform binary

inputs:
  terraform_version:
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Create output folder for Terraform binary
      run: mkdir -p output/terraform/files
      shell: bash
    - name: Copy Terraform binary to output folder
      run: cp $TERRAFORM_CLI_PATH/terraform-bin output/terraform/files/terraform
      shell: bash
    - name: Archive Terraform binary
      uses: actions/upload-artifact@v4
      with:
        name: terraform-bin
        path: output/terraform/files/terraform